## Cleaning the Data

In [115]:
import pandas as pd
import numpy as np
import re
from IPython.display import display

In [116]:
sales = pd.read_csv("../data/raw/synthetic/sales.csv")
customers = pd.read_csv("../data/raw/synthetic/customers.csv")
products = pd.read_csv("../data/raw/synthetic/products.csv")
stores = pd.read_csv("../data/raw/synthetic/stores.csv")
promotions = pd.read_csv("../data/raw/synthetic/promotions.csv")
holidays = pd.read_csv("../data/raw/synthetic/public_holidays.csv")
cpi = pd.read_csv("../data/raw/knbs/national_cpi_monthly.csv")

In [117]:

# Basic DataFrame Checks Function
def basic_df_checks(df_checks):

    print("=== BASIC DATAFRAME CHECKS ===")
    print(f"Shape: {df_checks.shape[0]} rows × {df_checks.shape[1]} columns\n")

    print("Column Data Types:")
    print(df_checks.dtypes)

    print("\nMissing Values:")
    print(df_checks.isnull().sum())

    print("\nDuplicate Rows:", df_checks.duplicated().sum())

    print("\n=== NUMERIC SUMMARY ===")
    numeric_cols = df_checks.select_dtypes(include=np.number).columns

    if len(numeric_cols) > 0:
        display(df_checks[numeric_cols].describe())
    else:
        print("No numeric columns found.")

    print("\n=== CATEGORICAL SUMMARY ===")
    categorical_cols = df_checks.select_dtypes(
        include=["object", "category", "string"]
    ).columns

    if len(categorical_cols) > 0:
        display(df_checks[categorical_cols].describe().T)
    else:
        print("No categorical columns found.")

    print("\nUnique Values per Column:")
    for col in df_checks.columns:
        print(f"{col}: {df_checks[col].nunique(dropna=True)}")

# Run the basic checks on the sales DataFrame
basic_df_checks(sales)

=== BASIC DATAFRAME CHECKS ===
Shape: 15000 rows × 10 columns

Column Data Types:
SaleID               int64
TransactionID          str
TransactionDate        str
CustomerID           int64
StoreID              int64
ProductID            int64
Quantity             int64
DiscountPct        float64
PromotionID        float64
PaymentMethod          str
dtype: object

Missing Values:
SaleID                 0
TransactionID          0
TransactionDate        0
CustomerID             0
StoreID                0
ProductID              0
Quantity               0
DiscountPct            0
PromotionID        13031
PaymentMethod          0
dtype: int64

Duplicate Rows: 0

=== NUMERIC SUMMARY ===

,SaleID,CustomerID,StoreID,ProductID,Quantity,DiscountPct,PromotionID
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,1969.000000
mean,7500.500000,501.932467,7.949533,50.683533,2.410067,2.132447,8.808024
std,4330.271354,288.537422,4.331124,28.833781,1.755406,5.279564,4.097108
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
25%,3750.750000,252.000000,4.000000,26.000000,1.000000,0.000000,6.000000
50%,7500.500000,504.000000,8.000000,51.000000,2.000000,0.000000,9.000000
75%,11250.250000,747.000000,12.000000,75.000000,3.000000,0.000000,12.000000
max,15000.000000,1000.000000,15.000000,100.000000,10.000000,25.000000,15.000000

=== CATEGORICAL SUMMARY ===

                 count unique                  top  freq
TransactionID    15000   5617                S-041     8
TransactionDate  15000   5617  2026-05-04 12:05:30     8
PaymentMethod    15000      3               M-Pesa  8125

Unique Values per Column:
SaleID: 15000
TransactionID: 5617
TransactionDate: 5617
CustomerID: 994
StoreID: 15
ProductID: 100
Quantity: 10
DiscountPct: 128
PromotionID: 15
PaymentMethod: 3

In [118]:
# Run the basic checks on the customers DataFrame
basic_df_checks(customers)

=== BASIC DATAFRAME CHECKS ===
Shape: 1000 rows × 5 columns

Column Data Types:
id                  int64
signup_date           str
last_name             str
age_group             str
customer_segment      str
dtype: object

Missing Values:
id                  0
signup_date         0
last_name           0
age_group           0
customer_segment    0
dtype: int64

Duplicate Rows: 0

=== NUMERIC SUMMARY ===

                id
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

=== CATEGORICAL SUMMARY ===

                 count unique         top freq
signup_date       1000    702  12/16/2024    5
last_name         1000    995        Duer    2
age_group         1000      5         55+  207
customer_segment  1000      4         New  257

Unique Values per Column:
id: 1000
signup_date: 702
last_name: 995
age_group: 5
customer_segment: 4

In [119]:
# Run the basic checks on the products DataFrame
basic_df_checks(products)

=== BASIC DATAFRAME CHECKS ===
Shape: 100 rows × 5 columns

Column Data Types:
ProductID         int64
ProductName         str
Category            str
UnitCostKsh     float64
UnitPriceKsh    float64
dtype: object

Missing Values:
ProductID       0
ProductName     0
Category        0
UnitCostKsh     0
UnitPriceKsh    0
dtype: int64

Duplicate Rows: 0

=== NUMERIC SUMMARY ===

        ProductID  UnitCostKsh  UnitPriceKsh
count  100.000000    100.00000    100.000000
mean    50.500000    365.18000    485.170000
std     29.011492    940.91193   1274.752993
min      1.000000     15.00000     25.000000
25%     25.750000     90.00000    125.000000
50%     50.500000    165.00000    230.000000
75%     75.250000    292.50000    372.500000
max    100.000000   8500.00000  11500.000000

=== CATEGORICAL SUMMARY ===

            count unique              top freq
ProductName   100    100  Maize Flour 2kg    1
Category      100      4             Food   40

Unique Values per Column:
ProductID: 100
ProductName: 100
Category: 4
UnitCostKsh: 40
UnitPriceKsh: 57

In [120]:
# Run the basic checks on the products DataFrame
basic_df_checks(products)

=== BASIC DATAFRAME CHECKS ===
Shape: 100 rows × 5 columns

Column Data Types:
ProductID         int64
ProductName         str
Category            str
UnitCostKsh     float64
UnitPriceKsh    float64
dtype: object

Missing Values:
ProductID       0
ProductName     0
Category        0
UnitCostKsh     0
UnitPriceKsh    0
dtype: int64

Duplicate Rows: 0

=== NUMERIC SUMMARY ===

        ProductID  UnitCostKsh  UnitPriceKsh
count  100.000000    100.00000    100.000000
mean    50.500000    365.18000    485.170000
std     29.011492    940.91193   1274.752993
min      1.000000     15.00000     25.000000
25%     25.750000     90.00000    125.000000
50%     50.500000    165.00000    230.000000
75%     75.250000    292.50000    372.500000
max    100.000000   8500.00000  11500.000000

=== CATEGORICAL SUMMARY ===

            count unique              top freq
ProductName   100    100  Maize Flour 2kg    1
Category      100      4             Food   40

Unique Values per Column:
ProductID: 100
ProductName: 100
Category: 4
UnitCostKsh: 40
UnitPriceKsh: 57

In [121]:
# Run the basic checks on the stores DataFrame
basic_df_checks(promotions)

=== BASIC DATAFRAME CHECKS ===
Shape: 15 rows × 5 columns

Column Data Types:
PromotionID      int64
PromotionName      str
StartDate          str
EndDate            str
DiscountPct      int64
dtype: object

Missing Values:
PromotionID      0
PromotionName    0
StartDate        0
EndDate          0
DiscountPct      0
dtype: int64

Duplicate Rows: 0

=== NUMERIC SUMMARY ===

       PromotionID  DiscountPct
count    15.000000    15.000000
mean      8.000000    14.933333
std       4.472136     5.351457
min       1.000000     8.000000
25%       4.500000    11.000000
50%       8.000000    15.000000
75%      11.500000    17.500000
max      15.000000    25.000000

=== CATEGORICAL SUMMARY ===

              count unique                       top freq
PromotionName    15     15  Mazingira Day Green Sale    1
StartDate        15     15                2025-10-08    1
EndDate          15     15                2025-10-12    1

Unique Values per Column:
PromotionID: 15
PromotionName: 15
StartDate: 15
EndDate: 15
DiscountPct: 6

In [122]:
# Run the basic checks on the stores DataFrame
basic_df_checks(stores)

=== BASIC DATAFRAME CHECKS ===
Shape: 15 rows × 4 columns

Column Data Types:
StoreID      int64
StoreName      str
Town           str
County         str
dtype: object

Missing Values:
StoreID      0
StoreName    0
Town         0
County       0
dtype: int64

Duplicate Rows: 0

=== NUMERIC SUMMARY ===

         StoreID
count  15.000000
mean    8.000000
std     4.472136
min     1.000000
25%     4.500000
50%     8.000000
75%    11.500000
max    15.000000

=== CATEGORICAL SUMMARY ===

          count unique              top freq
StoreName    15     15  Metro Retail 01    1
Town         15     15          Nairobi    1
County       15      5          Nairobi    3

Unique Values per Column:
StoreID: 15
StoreName: 15
Town: 15
County: 5

In [123]:
# Run the basic checks on the holidays DataFrame
basic_df_checks(holidays)

=== BASIC DATAFRAME CHECKS ===
Shape: 25 rows × 6 columns

Column Data Types:
date             str
holiday_name     str
day_of_week      str
observed_date    str
holiday_type     str
notes            str
dtype: object

Missing Values:
date              0
holiday_name      0
day_of_week       0
observed_date    23
holiday_type      0
notes             0
dtype: int64

Duplicate Rows: 0

=== NUMERIC SUMMARY ===
No numeric columns found.

=== CATEGORICAL SUMMARY ===

              count unique                   top freq
date             25     25            2024-10-10    1
holiday_name     25     13         Mazingira Day    2
day_of_week      25      5                Friday    9
observed_date     2      2            2024-10-21    1
holiday_type     25      3              National   14
notes            25     11  Fixed annual holiday    9

Unique Values per Column:
date: 25
holiday_name: 13
day_of_week: 5
observed_date: 2
holiday_type: 3
notes: 11

In [124]:
basic_df_checks(cpi)

=== BASIC DATAFRAME CHECKS ===
Shape: 141 rows × 5 columns

Column Data Types:
date               str
year             int64
month            int64
cpi            float64
base_period        str
dtype: object

Missing Values:
date           0
year           0
month          0
cpi            0
base_period    0
dtype: int64

Duplicate Rows: 0

=== NUMERIC SUMMARY ===

              year       month         cpi
count   141.000000  141.000000  141.000000
mean   2020.382979    6.404255  135.775142
std       3.405163    3.435069   26.430560
min    2015.000000    1.000000   94.740000
25%    2017.000000    3.000000  111.866000
50%    2020.000000    6.000000  137.032000
75%    2023.000000    9.000000  155.850000
max    2026.000000   12.000000  187.640000

=== CATEGORICAL SUMMARY ===

            count unique          top freq
date          141    141   2015-01-01    1
base_period   141      2  feb2019_100  105

Unique Values per Column:
date: 141
year: 12
month: 12
cpi: 141
base_period: 2

## Convert Date Columns to DT

In [125]:
# Convert all date columns to pandas datetime format
date_columns = {
    "sales": (sales, ["TransactionDate"]),
    "customers": (customers, ["signup_date"]),
    "promotions": (promotions, ["StartDate", "EndDate"]),
    "holidays": (holidays, ["date", "observed_date"]),
    "cpi": (cpi, ["date"]) 
}

for name, (df, columns) in date_columns.items():
    for col in columns:
        df[col] = pd.to_datetime(df[col], errors="coerce")
    print(f"{name}: date conversion complete")

# Verify the converted date columns
for name, (df, columns) in date_columns.items():
    print(f"\n{name.upper()}")
    print(df[columns].dtypes)

sales: date conversion complete
customers: date conversion complete
promotions: date conversion complete
holidays: date conversion complete
cpi: date conversion complete

SALES
TransactionDate    datetime64[us]
dtype: object

CUSTOMERS
signup_date    datetime64[us]
dtype: object

PROMOTIONS
StartDate    datetime64[us]
EndDate      datetime64[us]
dtype: object

HOLIDAYS
date             datetime64[us]
observed_date    datetime64[us]
dtype: object

CPI
date    datetime64[us]
dtype: object

## Standardize Column Names

In [126]:
def to_pascal(name: str) -> str:
    # Insert space before capitals that follow lowercase/digit, then title-case each word
    name = re.sub(r'(?<=[a-z0-9])([A-Z])', r' \1', name)
    name = name.replace("-", " ").replace("_", " ")
    return "".join(word.capitalize() for word in name.split())

def std_columns(df):
    df = df.copy()
    df.columns = [to_pascal(col) for col in df.columns]
    return df

# Apply the function to required datasets
customers = std_columns(customers)
holidays = std_columns(holidays)
cpi = std_columns(cpi)

# Display the standardized column names
for name, df in {
    "Sales": sales,
    "Customers": customers,
    "Products": products,
    "Stores": stores,
    "Promotions": promotions,
    "Public Holidays": holidays,
    "KNBS CPI": cpi
}.items():
    print(f"\n{name} columns:")
    print(df.columns.tolist())

Sales columns:
['SaleID', 'TransactionID', 'TransactionDate', 'CustomerID', 'StoreID', 'ProductID', 'Quantity', 'DiscountPct', 'PromotionID', 'PaymentMethod']

Customers columns:
['Id', 'SignupDate', 'LastName', 'AgeGroup', 'CustomerSegment']

Products columns:
['ProductID', 'ProductName', 'Category', 'UnitCostKsh', 'UnitPriceKsh']

Stores columns:
['StoreID', 'StoreName', 'Town', 'County']

Promotions columns:
['PromotionID', 'PromotionName', 'StartDate', 'EndDate', 'DiscountPct']

Public Holidays columns:
['Date', 'HolidayName', 'DayOfWeek', 'ObservedDate', 'HolidayType', 'Notes']

KNBS CPI columns:
['Date', 'Year', 'Month', 'Cpi', 'BasePeriod']

## Resolve Missing Values

In [127]:
# Drop the promotion ID column from the sales dataset
sales = sales.drop(columns=["PromotionID"])

# Confirm the column has been removed
print("Updated sales columns:")
print(sales.columns.tolist())

Updated sales columns:
['SaleID', 'TransactionID', 'TransactionDate', 'CustomerID', 'StoreID', 'ProductID', 'Quantity', 'DiscountPct', 'PaymentMethod']

In [128]:

# Fill missing observed dates with the actual holiday dates assuming the holiday was observed on its listed date.
holidays["ObservedDate"] = holidays["ObservedDate"].fillna(holidays["Date"])
print(holidays["ObservedDate"].isnull().sum())

# Display the holiday dates and observed dates for verification
display(
    holidays[["Date", "HolidayName", "ObservedDate"]].head(10)
)

0

        Date              HolidayName ObservedDate
0 2024-10-10            Mazingira Day   2024-10-10
1 2024-10-20             Mashujaa Day   2024-10-21
2 2024-11-01  Kindiki Swearing-in Day   2024-11-01
3 2024-12-12              Jamhuri Day   2024-12-12
4 2024-12-25            Christmas Day   2024-12-25
5 2024-12-26            Utamaduni Day   2024-12-26
6 2025-01-01           New Year's Day   2025-01-01
7 2025-03-31              Idd ul-Fitr   2025-03-31
8 2025-04-18              Good Friday   2025-04-18
9 2025-04-21            Easter Monday   2025-04-21

## Correct Spelling Inconsistency

In [129]:
customers["CustomerSegment"] = customers["CustomerSegment"].replace(
    "Occassional", "Occasional")

print(customers["CustomerSegment"].value_counts())

CustomerSegment
New           257
Occasional    253
Lapsed        252
Regular       238
Name: count, dtype: int64

In [130]:
# Prefer Parquet (keeps datetime, categories, etc.)
sales.to_parquet("../data/cleaned/sales_cleaned.parquet", index=False)
customers.to_parquet("../data/cleaned/customers_cleaned.parquet", index=False)
products.to_parquet("../data/cleaned/products_cleaned.parquet", index=False)
stores.to_parquet("../data/cleaned/stores_cleaned.parquet", index=False)
holidays.to_parquet("../data/cleaned/public_holidays_cleaned.parquet", index=False)
promotions.to_parquet("../data/cleaned/promotions_cleaned.parquet", index=False)
cpi.to_parquet("../data/cleaned/national_cpi_monthly_cleaned.parquet", index=False)

print("All cleaned datasets have been saved!")

All cleaned datasets have been saved!

## Data Cleaning Summary

- Standardized column names.
- Converted `TransactionDate` in sales, `signup_date` in customers, `StartDate` and `EndDate` in promotions, and `Date` and `ObservedDate` in holidays to datetime format.
- Dropped the `PromotionID` column from the sales dataset.
- Filled missing `ObservedDate` values using `Date`.
- Corrected the customer segment spelling from `Occassional` to `Occasional`.
- Saved all seven datasets to the `data/cleaned/` folder.